<header class="sassdoc__header">
  <div class="container">
    <h1 class="sassdoc__title">{{ title }}</h1>

    <div class="sassdoc__searchbar  searchbar">
      <label for="js-search-input">Search</label>
      <form class="searchbar__form">
        <input name="search" type="search" class="searchbar__field" autocomplete="off" autofocus id="js-search-input" />
        <ul class="searchbar__suggestions" id="js-search-suggestions"></ul>
      </form>
    </div>
  </div>
</header>